name: Build & Publish Wheels

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request: { }
  push:
    tags:
      - 'v*'

jobs:
  build-wheels:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build tool
        run: python -m pip install --upgrade build

      - name: Install wxPython based on OS
        run: python install_wxpython.py

      - name: Build wheel
        run: python -m build --wheel --outdir dist

      - name: Upload wheel artifact (${ { matrix.python-version } })
        uses: actions/upload-artifact@v4
        with:
          name: CTPv-wheel-${{ matrix.python-version }}
          path: dist/*.whl

  publish:
    name: Publish to GitHub Release & PyPI
    needs: build-wheels
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/project/CTPv
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Download all wheels
        uses: actions/download-artifact@v4
        with:
          path: downloaded-artifacts

      - name: Find and move distribution files to 'dist' directory
        run: |
            mkdir dist
            find downloaded-artifacts -name "*.whl" -exec mv {} dist/ \;

      - name: Create / Update GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: 'dist/*.whl'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to PyPI via trusted publisher
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ''
